from crewai.tools import tool
import os
from pathlib import Path
import requests 
from typing import Type
from pptx import Presentation           
from pydantic import BaseModel, Field


@tool("Create PowerPoint")
def create_powerpoint(presentation_content: str) -> str:
    """
    Create a PowerPoint presentation from the presentatation content generated by Presentation Agent.
    Args:
        presentation_content: The complete presentation content generated by the Presentation Agent.

    Returns:
        Path of the generated PowerPoint file.
    """
    output_dir = Path("output")
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "presentation-1.pptx"

    prs = Presentation()

    # Title slide
    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = "Research Report"

    # Content slide
    content_slide = prs.slides.add_slide(prs.slide_layouts[1])
    content_slide.shapes.title.text = "Research Findings"
    content_slide.placeholders[1].text = presentation_content


    prs.save(output_path)

    return f"PowerPoint created successfully: {output_path}"
